### ISSUE TITLE
Fails on step "Determine path to libvirt environment file"

### ISSUE THREAD

**Issue by michmill1970** [stackhpc/ansible-role-libvirt-host#13]
I'm trying to use the Libvirt-host role on a fresh install of Ubuntu 18.04 and it fails on step "Determine path to libvirt environment file".  It can't find the files /etc/default/libvirt-bin or /etc/default/libvirtd, but /etc/default/libvirtd does exist on the target machine.  However, if I copy /etc/default/libvirtd to the Ansible controller everything works fine.

I appears the "with_first_found" is looking on the wrong machine.

Ansible version: 2.7.8
Target: Ubuntu 18.04.2 LTS

Playbook libvirt-host.yaml:
-
  name: Configure Libvirt/KVM system
  hosts: libvirt_servers
  become: yes
  roles:
    - role: stackhpc.libvirt-host
      libvirt_host_pools:
        - name: pool01
          type: dir
          capacity: 20840
          path: /var/lib/libvirt/images
          mode: 755
          owner: root
          group: root
      libvirt_host_networks:
        - name: virbr0
          mode: bridge
          bridge: virbr0

-vvv output:
TASK [stackhpc.libvirt-host : Ensure QEMU emulator packages are installed] ****************************************************************
task path: /etc/ansible/roles/stackhpc.libvirt-host/tasks/install.yml:32

TASK [stackhpc.libvirt-host : Run post-install stage] *************************************************************************************
task path: /etc/ansible/roles/stackhpc.libvirt-host/tasks/main.yml:5
included: /etc/ansible/roles/stackhpc.libvirt-host/tasks/post-install-Debian.yml for ubuntu-kvm-01.digitalwaterworks.com

TASK [stackhpc.libvirt-host : Determine path to libvirt environment file] *****************************************************************
task path: /etc/ansible/roles/stackhpc.libvirt-host/tasks/post-install-Debian.yml:3
fatal: [ubuntu-kvm-01.digitalwaterworks.com]: FAILED! => {
    "msg": "No file was found when using with_first_found. Use the 'skip: true' option to allow this task to be skipped if no files are found"
}
	to retry, use: --limit @/root/ansible/libvirt-host/configure_libvert_host.retry

PLAY RECAP ********************************************************************************************************************************
ubuntu-kvm-01.digitalwaterworks.com : ok=6    changed=0    unreachable=0    failed=1

**Comment by markgoddard** [comment]
Thanks for raising this. I've proposed a fix, just running through some tests.

**Comment by jovial** [comment]
Fixed with #14. Please reopen if you still have issues.
