### ISSUE TITLE
libvirt_host_networks not creating a bridge on the machine for the new network to use

### ISSUE THREAD

**Issue by nathanjmartin** [stackhpc/ansible-role-libvirt-host#15]
`libvirt_host_networks:
        - name: br-example
          mode: bridge
          bridge: br0`

Does not create br0 on the machine for the network to use.
Does this role assume the bridge is already created on the local machine?

**Comment by markgoddard** [comment]
Yes - we only generate the libvirt network XML config, and don't create the bridge.

**Comment by nathanjmartin** [comment]
Okay gotcha, thanks for the quick reply.
