### ISSUE TITLE
Allow creation of isolated network

### ISSUE THREAD

**Issue by Desnoo** [stackhpc/ansible-role-libvirt-host#38]
This is a little feature request.

It would be great to define an isolated network. This can be achieved if the <forward/> definition is conditionally removable from the `network.xml.j2` template.

As flag the mode definition could be used if it is not set by standard values.

**Comment by markgoddard** [comment]
hi @Desnoo. If you propose the code, we will review it.

**Comment by IncredibleRichie** [comment]
Created pull request
https://github.com/stackhpc/ansible-role-libvirt-host/pull/53
