### ISSUE TITLE
small issue on the README

### ISSUE THREAD

**Issue by roumano** [stackhpc/ansible-role-libvirt-host#41]
Small issue in the README about the documentation :
```
pvs A list of physical volumes the volume group consists of. (only when
```
the line is cut before the ned

Maybe `only when it's lvm volume` ?

**Comment by jovial** [comment]
It used to read: ``source` The name of the volume group. (only when type is `logical`)`. I guess that should be lvm2 or logical:

https://github.com/stackhpc/ansible-role-libvirt-host/blob/2f47f93d5a94ae02c54c60d40137b74751d2f869/tasks/pools.yml#L17

**Comment by markgoddard** [comment]
Thanks. Looks like a broken merge.
